
mode=deploy
device=/dev/video0
width=160
height=120
fps=120
fourcc=MJPG
ui=1

warp_width=384
warp_height=384
target_tag_px=128
tag_family=auto
target_id=0
manual_lock_only=1
lock_frames=4

save_warp=../report/warp_package.yml.gz
load_warp=../report/warp_package.yml.gz
save_rois=../report/rois.yml
load_rois=../report/rois.yml
save_report=../report/latest_report.md

red_roi=0.08,0.08,0.18,0.18
image_roi=0.32,0.10,0.50,0.55

red_h1_low=0
red_h1_high=10
red_h2_low=170
red_h2_high=180
red_s_min=80
red_v_min=60

model_enable=1
model_backend=off
model_onnx_path=../models/best.onnx
model_ncnn_param_path=../models/model.ncnn.param
model_ncnn_bin_path=../models/model.ncnn.bin
model_labels_path=../models/labels.txt
model_input_width=128
model_input_height=128
model_preprocess=crop
model_threads=4
model_stride=1
model_max_hz=5.0
model_topk=5

run_red=1
run_image_roi=1
run_model=1
save_every_n=0

overlay_text=1